name: LieAlgDB
version: "2.3.0"
license: "GPL-2.0-or-later"
date: 2025-09-24
description: |
    A database of Lie algebras

authors:
    - name: Serena Cicalò
      url: mailto:cicalo@science.unitn.it
    - name: Willem Adriaan de Graaf
      url: http://www.science.unitn.it/~degraaf
    - name: Csaba Schneider
      url: http://www.mat.ufmg.br/~csaba/

maintainers:
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">= 4.8"

www: https://gap-packages.github.io/liealgdb/
readme: README
packageinfo: https://gap-packages.github.io/liealgdb/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/liealgdb/releases/download/v2.3.0/liealgdb-2.3.0.tar.gz

abstract: |

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    Lie algebras.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>CGST25</span>]   <b class='BibAuthor'>Cicalò, S., de Graaf, W. A., Schneider, C. and GAP Team, T.</b>,
     <i class='BibTitle'>LieAlgDB, A database of Lie algebras,
             Version 2.3.0</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/liealgdb/">https://gap-packages.github.io/liealgdb/</a></span>.
    </p>
    

bibtex: |
    @misc{ LieAlgDB,
      author =           {Cical{\a`o},  S. and de Graaf, W. A. and Schneider, C.
                          and GAP Team, T.},
      title =            {{LieAlgDB},  {A  database  of Lie algebras}, {V}ersion
                          2.3.0},
      month =            {Sep},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href       {https://gap-packages.github.io/liealgdb/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{liealgdb/}}},
      keywords =         {Lie algebras},
      printedkey =       {CGST25}
    }

