name: LieAlgDB
version: 2.2
date: 2018-04-09
description: |
    A database of Lie algebras

authors:
    - name: Serena Cicalò
      url: mailto:cicalo@science.unitn.it
    - name: Willem de Graaf
      url: http://www.science.unitn.it/~degraaf
    - name: Csaba Schneider
      url: http://www.mat.ufmg.br/~csaba/

maintainers:
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">= 4.8"

www: https://gap-packages.github.io/liealgdb/
readme: README
packageinfo: https://gap-packages.github.io/liealgdb/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/liealgdb/releases/download/v2.2/liealgdb-2.2.tar.gz

abstract: |

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
