name: liealgdb
version: 2.1
date: 2010-03-28
description: |
    A database of Lie algebras

authors:
    - name: Serena Cicalo'
      url: mailto:cicalo@science.unitn.it
    - name: Willem de Graaf
      url: http://www.science.unitn.it/~degraaf
    - name: Csaba Schneider
      url: http://www.sztaki.hu/~schneider

maintainers:
    - name: Serena Cicalo'
      url: mailto:cicalo@science.unitn.it
    - name: Willem de Graaf
      url: http://www.science.unitn.it/~degraaf
    - name: Csaba Schneider
      url: http://www.sztaki.hu/~schneider

GAP: ">= 4.7"

www: http://www.sztaki.hu/~schneider/Research/LieAlgDB/
readme: README
packageinfo: http://www.sztaki.hu/~schneider/Research/LieAlgDB/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://www.sztaki.hu/~schneider/Research/LieAlgDB/liealgdb2r0p2.tar.gz

abstract: |
    http://www.sztaki.hu/~schneider/Research/LieAlgDB/

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
